baseURL1 = "http://example.org/"
baseURL="http://localhost:1313/learning/"
relativeurls = false
languageCode = "en-us"
publishDir="docs"
title = "Learning 101"
disqusShortname = "dev-learning"
pygmentsUseClasses=true
pygmentsOptions= "linenos=table, startinline=true"
Paginate=2
[taxonomies]
  category="categories"
  tag="tags"
  author="authors"
[outputs]
home = [ "HTML", "RSS", "JSON"]
[params.dhaka]
[params.dhaka.polo]
  name = "Polo Dev"
  bio = "Polo Dev is a Educator. He completed his graduation in Marketing and later did a post graduation diploma in IT"
  location = "Dhaka, Bangladesh"
  email = "polodev10@gmail.com"
  twitter=  "polodev10"
  image = "/images/author/polodev.jpg"
